### ISSUE TITLE
whats the difference between cpu version and gpu version? how to choose from them?

### ISSUE THREAD

**Issue by PeixuanGao** [engcang/vins-application#10]

**Comment by engcang** [comment]
Hi. sorry for late.
CPU version only consumes CPU to solve optimization with `Ceres` solver.
It also utilizes CPU to process image things with `OpenCV`.

GPU version also consumes only CPU to solve optimization with `Ceres`.
But it utilizes GPU to process image things with `OpenCV` with `CUDA` enabled.

Thanks.
