### ISSUE TITLE
USB Performance ./flash.sh

### ISSUE THREAD

**Issue by Zhefan-Xu** [engcang/vins-application#12]
Hi, could you provide more information on the USB performance section especially for ./flash.sh file? I am quite sure where this file comes from.

Thanks!

**Comment by engcang** [comment]
Are you asking where you can get `flash.sh` file?
If you download and install `SDK_manager` for NVIDIA `Jetpack` installations,
There will be a folder for the `SDK_manager`, inside the folder, you can find the `flash.sh` file after download specific version of `Jetpack` using the manager.
