### ISSUE TITLE
Can't find the proper launch file for d435i

### ISSUE THREAD

**Issue by ArghyaChatterjee** [engcang/vins-application#13]
Hi, 
I can't find the file which launches vins fusion node. I have a d435i. I have launched the `rs_camera.launch` file but stuck in launching node which launches vins/vins estimator. I can't see any launch file. The only launch file that I see is `kaist.launch` which is configured for stereo camera I think (most probably for T265). Any help is appreciated. Thanks !!

**Comment by engcang** [comment]
Hi. sorry for late.

You have to launch camera with `rs_camera.launch` first, then run `VINS-Fusion` with
~~~bash
$ rosrun vins vins_node absolute_path_to_the_name_of_config_file.yaml

e.g.,

$ rosrun vins vins_node /home/mason/realsense_stereo_imu_config.yaml
~~~

You can find proper d435i's config file from here: https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/tree/master/config/realsense_d435i

But, make sure to set the same image width and height in the `rs_camera.launch` file
