### ISSUE TITLE
Test VID Fusion

### ISSUE THREAD

**Issue by dssdyx** [engcang/vins-application#15]
There is a new VINS with rotos' dynamic called VID-Fusion. Do you plan to test this new one?

**Comment by engcang** [comment]
Wow. Thank you for suggestion @dssdyx .
However, sadly I am not planning to purchase optical encoder nor hall sensor for measuring the rotor thrust of drones.

If you find some other algorithms to recommend, please tell me!
Thank you.
Eungchang Lee.

**Comment by dssdyx** [comment]
> Wow. Thank you for suggestion @dssdyx . However, sadly I am not planning to purchase optical encoder nor hall sensor for measuring the rotor thrust of drones.
> 
> If you find some other algorithms to recommend, please tell me! Thank you. Eungchang Lee.

OK
