### ISSUE TITLE
Test dm-vio

### ISSUE THREAD

**Issue by dssdyx** [engcang/vins-application#17]
Dm-vio is dso vio version. It seems to be light and accuracy. Are you interested to test it?

**Comment by engcang** [comment]
Thank you for your suggestion @dssdyx

I tested it on KAIST-VIO dataset and the result video is here - https://youtu.be/OJddYxLlSqo
It is not that light as the CPU usage of VINS-Mono is similar to the DM-VIO and VINS-Mono showed more stable and accurate performance.

Thanks.
