### ISSUE TITLE
Question about building VINS-Fusion with GPU support using OpenCV 4.6.0

### ISSUE THREAD

**Issue by ranjithlesoko** [engcang/vins-application#20]
I'm trying to build VINS-Fusion with GPU support using OpenCV 4.6.0, but I'm encountering some difficulties. Specifically, I'm unsure about the correct configuration and build steps required to enable GPU acceleration with OpenCV 4.6.0.

I've already followed the installation instructions for VINS-Fusion and have successfully built it without GPU support. However, I'm not sure how to incorporate OpenCV 4.6.0 with CUDA support into the build process to enable GPU acceleration.

Could someone provide guidance or pointers on how to correctly configure and build VINS-Fusion with GPU support using OpenCV 4.6.0?

Environment:

Operating System: Ubuntu 20.04
OpenCV Version: 4.6.0
CUDA Toolkit Version: 11.4
Model: jetson xevier nx

**Comment by engcang** [comment]
@ranjithlesoko Hi.
I want to first ask you if you followed all instructions written in this repository's readme.
There already I wrote how to install OpenCV with CUDA, cv_bridge after CUDA+OpenCV, and VINS-Fusion-Gpu version at:

https://github.com/engcang/vins-application?tab=readme-ov-file#-opencv-with-cuda-and-cudnn
https://github.com/engcang/vins-application?tab=readme-ov-file#-cv_bridge-with-built-opencv-necessary-for-whom-built-opencv-manually-from-above
https://github.com/engcang/vins-application?tab=readme-ov-file#-vins-fusion-1

**Comment by ranjithlesoko** [comment]
@engcang   i have reviewed the README file detailing how to build VINS-Fusion with GPU support using OpenCV 3, but I am specifically interested in instructions for integrating VINS-Fusion with GPU acceleration using OpenCV 4.6.

**Comment by ranjithlesoko** [comment]
@engcang  I'm experiencing low frame rates (5-8 fps) when using VINS-Fusion on my Jetson, and I've noticed drifting in the IMU measurements. How can I address these issues for smoother performance and more accurate pose estimation?

**Comment by ranjithlesoko** [comment]
@engcang  ?
