### ISSUE TITLE
Using with Intel RealSense T265 

### ISSUE THREAD

**Issue by sumitsarkar1** [engcang/vins-application#5]
1.) Has any one used T265 with VINS Fusion
2.) Which is the convenient way calibrating T265 for VINS Fusion (like using Kalibr), if atall required.

**Comment by engcang** [comment]
1) Yes. look here: [reference](https://www.jianshu.com/p/194d6c9ef9a4), which is only written in Chinese and even I do not understand what the author says.

2) But thanks to few English words, I found that he used `Kalibr` with `omni-radtan` models for T265 stereo fisheye cameras.
and used it with `MEI` camera model in `.yaml` file.

3) Also, try [this repo, VINS-Fisheye](https://github.com/xuhao1/VINS-Fisheye) from the original authors of VINS-Fusion.

**Comment by engcang** [comment]
@sumitsarkar1  
Hi. If you are still interested in operating VINS Fusion with T265,
I tested it recently following the steps I mentioned above.

Here is the result clip: https://youtu.be/8w86LeB6fns

**Comment by sumitsarkar1** [comment]
Great work !! can you share the yaml file and one more querry...does VINS-Fisheye allow map saving or can we do it through ROS. Sorry I am just a beginner in ROS !!

**Comment by engcang** [comment]
@sumitsarkar1 yaml files can be found at this repo's other branch (T265 branch): https://github.com/engcang/vins-application/tree/Intel-T265
Map saving is not supported in VINS-Fusion nor VINS-Fisheye as far as I know.
Lots of works were made to save the map and reuse it within ORB-SLAM2 frame works, you have to check that.

**Comment by sumitsarkar1** [comment]
Thnx for the infos....ya map saving is lots of work...I tried it once !!!...do you know any repo for ORB_SLAM2 which allows map saving ...and reloading it for localisation only

**Comment by engcang** [comment]
@sumitsarkar1 
Check out my other repo: https://github.com/engcang/orb-slam2-modified
check the mal_local branch, I forked the map saving ORB-SLAM2 there.
