### ISSUE TITLE
Masking file

### ISSUE THREAD

**Issue by vicente879** [engcang/vins-application#7]
Hello, thank you for your explanations. 

I am confused about the mask added to the VINS-Fusion for PX4
 1. what is the image used to create this mask in maskin.m?
 2. Does a different mask need to be used if using the d435i with different resolution (I'm guessing yes but making sure)
 3. What is improved by using this mask? 

Thank you

**Comment by engcang** [comment]
@vicente879 
Hi. thanks for your interest in my repo.
1. That image is the one captured from a camera attached on my drone, and the black part in the image shows the propeller guard. I needed to delete the feature points within that area to prevent the unstable VIO result.
2. Yes! with the resolution you are going to use.
3. The mask is used within setMask() function in the featureTracker.cpp, which deletes the feature points detected from GFTT within the mask area. By deleting unnecessary (or undesirable) feature points, more precise odometry will be optimized by solving less residuals.

**Comment by EhrazImam** [comment]
Hi @engcang how did you make the masking image can you refer from where we can make our own custom masking image.
Thankyou

**Comment by engcang** [comment]
@EhrazImam Hi. Please refer the comment above and [this file](https://github.com/engcang/vins-application/blob/master/vins-fusion-px4/masking.m) and the result masking image [here](https://github.com/engcang/vins-application/blob/master/vins-fusion-px4/mask_img.jpg)

**Comment by EhrazImam** [comment]
Hi @engcang thankyou for your reply, As you mentioned "black part in the image shows the propeller guard". I am able to make it for circular but how you are doing it for the black srtip like masking. as you can see over here
![mask](https://user-images.githubusercontent.com/88690390/229533918-abd14c5c-deb6-4862-981a-88eb0ba3210d.png)

**Comment by engcang** [comment]
@EhrazImam 
I actually do not understand what your question is! Are you asking how I made the masking image? Just take picture with the camera which you want to use, and process the image.

With the camera I want to use, I took a picture (any picture, since there always exists the masking area within the image) and save it. With the saved picture, there we can figure out where we should mask. 
So, as I mentioned above, I use the MATLAB file to read the saved image and process the image into black and white masking image.

**Comment by EhrazImam** [comment]
Hi @engcang What i am asking is how to do masking for the desired part of the image as you can see in the above image.
thankyou

**Comment by engcang** [comment]
@EhrazImam 
Hey. I hope my former answer is the one. I think I already explained enough there.

**Comment by ynma-hanvo** [comment]
i guess need to use some external tool like Photoshop to mask out pixels by pixel;

**Comment by engcang** [comment]
@ynma-hanvo Yep. That can be one of the options!
