### ISSUE TITLE
Using Vins with d435i realsense camera

### ISSUE THREAD

**Issue by bhaskar-glitch** [engcang/vins-application#8]
Hi @engcang ,
I'm using vins with d435i camera and I'm using image of camera only not the imu of it because when we're enabling the imu the vins is getting extreme distorted,also we have done imu calibration perfectly and the calibration data is also perfect but i don't why it's getting distorted although vins is working great with image only so im using it for now.Now I'm facing an orientation problem in vins like in vins rviz the camera is in upward direction also when we move our drone upward the value of -y is increasing and when we are moving our drone forward the z is increasing...
Please help regarding the issue

**Comment by engcang** [comment]
@bhaskar-glitch 
Hi. 

1. VINS is publishing its estimated pose in the coordinate obtained from the `.yaml` config file.
Forward direction of camera is +Z and Right direction of camera is +X, downward direction is +Y basically.
Refer this picture
https://github.com/engcang/vins-application/blob/master/extrinsic.png
If the direction of your result is different from the picture I attatched, 
then anyway the result is based on the coordinate obtained from your `.yaml` file.
You should change the body_T_cam matrix in the file, and you will see the transformed results.

2. You can get the proper estimated pose using only stereo but not with IMU? I strongly doubt your calibration data is wrong.
How can you assure that your calibration is perfect? Please show me the calibration data and results.

3. If the calibration data, results, and your `.yaml` config files are proper, the IMU data itself is wrong. For examples, too cheap and low performanced IMU.

**Comment by EhrazImam** [comment]
[
[results-imucam-homeespmehrazcamera_imu_calibration.txt](https://github.com/engcang/vins-application/files/7675991/results-imucam-homeespmehrazcamera_imu_calibration.txt)
](url)

**Comment by EhrazImam** [comment]
%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0      
num_of_cam: 2  

imu_topic: "/camera/imu"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"
output_path: "/home/enord/output/"

cam0_calib: "left1.yaml"
cam1_calib: "right1.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.999903, -0.01201376, 0.00704661, -0.04538521,
           0.01182784, 0.99959566, 0.02585779, -0.01626158,
           -0.00735441, -0.02577194, 0.9996408, -0.02162864,
           0.0, 0.0, 0.0, 1.0] 
   #data: [ 0.999903, 0.01182784, -0.00735441, 0.04541408, -0.01201376, 0.99959566, -0.02577194, 0.01515235, 0.00704661, 0.02585779, 0.9996408, 0.02236117, 0.0, 0.0, 0.0, 1.0]                                                 

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.99991698, -0.01215467, 0.00427759, 0.00421362,
           0.01204525, 0.99962138, 0.02473868, -0.01624456,
           -0.00457666, -0.0246851, 0.9996848, -0.02160395,
           0.0, 0.0, 0.0, 1.0] 
   #data: [ 0.99991698, 0.01204525, -0.00457666, -0.00411648, -0.01215467, 0.99962138, -0.0246851, 0.01575633, 0.00427759, 0.02473868, 0.9996848, 0.02198099, 0.0, 0.0, 0.0, 1.0]

#Multiple thread support
multiple_thread: 1
use_gpu: 1
use_gpu_acc_flow: 1

#feature traker paprameters
max_cnt: 350            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)
  
#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.00                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 1

**Comment by engcang** [comment]
@EhrazImam 
You are using `T_ci` values of calibration results.txt file for `body_T_cam0` and `body_T_cam1` in `.yaml` file.
But you should use `T_ic`' values instead. 

`T_ci` and `T_ic` values are almost same, so that was not a big deal.
Rather, IMU data should be improper, I think.
Since you have huge timeshift between cams and IMU in your calubraiton.txt file.

Refer my result with d435i : [here](https://github.com/engcang/vins-application/blob/Intel-D435i/kalibr_d435i/results-imucam-d435i.txt)
As you can see there, `T_ic` value is quite different from yours. 
Even the coordinate of your d435i is slightly weird.

**Comment by EhrazImam** [comment]
Hi @engcang Thanx for your quick reply..
Yeah I found out theres a big difference btwn your T_ic and mine... Any Solution to resolve this.
I have calibrated more than 4/5 time and i found out same issue..
While I am using T_ci value the results are good but as soon as i use T_ic and imu it start acting like crazy

**Comment by engcang** [comment]
@EhrazImam 

If you refer the results from the others [here](https://github.com/engcang/vins-application/issues/2)
Your values are similar to them. 
However, the `timeshift` is still to bigger than the others. 
I think you have some IMU problem and I have no idea with that. You can ask this at official Realsense github maybe!

**Comment by EhrazImam** [comment]
Ok..
How can i change the orientation without using imu.
As i am using Imu= 0 the orientation of camera is z as forward y as downward...How can change this

**Comment by EhrazImam** [comment]
I recorded the bag file at IMU at 400 hz and Image topic at 20 after calibrating using kalibr i got this result

Calibration results
===================
Normalized Residuals
----------------------------
Reprojection error (cam0):     mean 0.185263017312, median 0.158308068528, std: 0.122380681672
Reprojection error (cam1):     mean 0.184833179058, median 0.158783483975, std: 0.119868206343
Gyroscope error (imu0):        mean 0.482082868432, median 0.360998598228, std: 0.405424466949
Accelerometer error (imu0):    mean 0.788369825131, median 0.599966681382, std: 0.665111053117

Residuals
----------------------------
Reprojection error (cam0) [px]:     mean 0.185263017312, median 0.158308068528, std: 0.122380681672
Reprojection error (cam1) [px]:     mean 0.184833179058, median 0.158783483975, std: 0.119868206343
Gyroscope error (imu0) [rad/s]:     mean 0.0180154367933, median 0.0134905176158, std: 0.0151507123299
Accelerometer error (imu0) [m/s^2]: mean 0.0294061944774, median 0.0223787572156, std: 0.0248086422813

Transformation (cam0):
-----------------------
T_ci:  (imu0 to cam0): 
[[ 0.99970093 -0.01920286  0.01514269 -0.03767006]
 [ 0.01809064  0.99735141  0.07044788 -0.0238645 ]
 [-0.01645539 -0.07015287  0.99740052 -0.01472443]
 [ 0.          0.          0.          1.        ]]

T_ic:  (cam0 to imu0): 
[[ 0.99970093  0.01809064 -0.01645539  0.03784823]
 [-0.01920286  0.99735141 -0.07015287  0.02204496]
 [ 0.01514269  0.07044788  0.99740052  0.01693778]
 [ 0.          0.          0.          1.        ]]

timeshift cam0 to imu0: [s] (t_imu = t_cam + shift)
-0.10835458014072932


Transformation (cam1):
-----------------------
T_ci:  (imu0 to cam1): 
[[ 0.99975815 -0.01932439  0.01049807  0.01191344]
 [ 0.0185555   0.99744628  0.06896825 -0.02384895]
 [-0.01180403 -0.06875678  0.99756362 -0.01489528]
 [ 0.          0.          0.          1.        ]]

T_ic:  (cam1 to imu0): 
[[ 0.99975815  0.0185555  -0.01180403 -0.01164385]
 [-0.01932439  0.99744628 -0.06875678  0.02299411]
 [ 0.01049807  0.06896825  0.99756362  0.01637874]
 [ 0.          0.          0.          1.        ]]

timeshift cam1 to imu0: [s] (t_imu = t_cam + shift)
-0.10853589484165398

Baselines:
----------
Baseline (cam0 to cam1): 
[[ 0.9999892  -0.00044738 -0.00462497  0.04950432]
 [ 0.00044049  0.99999879 -0.00149008  0.00001017]
 [ 0.00462563  0.00148803  0.99998819  0.00003873]
 [ 0.          0.          0.          1.        ]]
baseline norm:  0.0495043347527741 [m]


Gravity vector in target coords: [m/s^2]
[-0.12232197  9.8057259  -0.03463783]


Calibration configuration
=========================

cam0
-----
  Camera model: pinhole
  Focal length: [389.9600039939013, 390.5946033063665]
  Principal point: [320.8658150643228, 239.22836792604002]
  Distortion model: radtan
  Distortion coefficients: [0.011837273394374846, -0.007737034630633963, -0.0010864828386214585, -0.00013982336228869968]
  Type: aprilgrid
  Tags: 
    Rows: 6
    Cols: 6
    Size: 0.024 [m]
    Spacing 0.00699999999984 [m]


cam1
-----
  Camera model: pinhole
  Focal length: [390.0250990935741, 390.65015130557606]
  Principal point: [322.38876735415346, 239.73648698119453]
  Distortion model: radtan
  Distortion coefficients: [0.012567609446704469, -0.009093774535987009, -0.0010117986832061956, 0.0011809391359000974]
  Type: aprilgrid
  Tags: 
    Rows: 6
    Cols: 6
    Size: 0.024 [m]
    Spacing 0.00699999999984 [m]



IMU configuration
=================

IMU0:
----------------------------
  Model: calibrated
  Update rate: 400.0
  Accelerometer:
    Noise density: 0.001865 
    Noise density (discrete): 0.0373 
    Random walk: 0.0002
  Gyroscope:
    Noise density: 0.0018685
    Noise density (discrete): 0.03737 
    Random walk: 4e-06
  T_i_b
    [[1. 0. 0. 0.]
     [0. 1. 0. 0.]
     [0. 0. 1. 0.]
     [0. 0. 0. 1.]]
  time offset with respect to IMU0: 0.0 [s]
