### ISSUE TITLE
Error in realsense-viewer

### ISSUE THREAD

**Issue by Kaijun101** [engcang/vins-application#9]
| Required Info                         |                                                                |
|---------------------------------|------------------------------------------- |
| Camera Model                       | D435i | 
| Firmware Version                   | 05.12.13.50| 
| Operating System & Version |   Ubuntu 18.04 | 
| Kernel Version (Linux Only)    |         4.9.140-tegra  | 
| Platform                                 | NVIDIA Jetson   |
| SDK Version                            |  v2.45.0                          | 
| Language                            |  C                    | 
| Segment			|  Robot- ROS v2.3.0             | 

### Issue Description
I am currently using auvidea j120 board with jetson TX2 and D435i.
However, there is some error i am currently facing when i am running realsense-viewer. The D435i camera does not have RGB image and is showing this error.

<pre>ERROR [547423751968] (synthetic-stream.cpp:48) Exception was thrown during user processing callback: 1kernel_other_to_depthILi4EEvPhPKhPK4int2PK14rs2_intrinsicsS8_</pre>

**Steps taken**
 $ sudo apt-get install git libssl-dev libusb-1.0-0-dev pkg-config libgtk-3-dev
 $ sudo apt-get install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev
 $ git clone https://github.com/IntelRealSense/librealsense.git
 $ cd librealsense
 $ git checkout v2.45.0
 $ mkdir build && cd build
 $ cmake .. -DCMAKE_BUILD_TYPE=Release -DFORCE_RSUSB_BACKEND=ON -DBUILD_WITH_CUDA=true
 $ sudo make uninstall && make clean
 $ time make -j8 && sudo make install
 
 **Below is the image of the realsense-viewer for your references**
![image](https://user-images.githubusercontent.com/90491438/150711919-45d24fc1-c961-4347-8200-1358ee76f146.png)

**Comment by Kaijun101** [comment]
@engcang

**Comment by engcang** [comment]
Hi @Kaijun101.

1. To the best of my knowledge, to use J120 carrier board's USB ports properly, you should refresh the kernel of the TX2 board using the firmware from Auvidea - [link](https://auvidea.eu/firmware/). Or, you cannot use USB ports successfully. 
Did you do that?

Beside that, I haven't met that kind of error before.
I would downgrade the firmware of the camera.
I guess it could be the solely problem of the camera and if you want to check that, try to run 'camera' application in Windows10 with the d435i, if RGB image comes in or not.

Sorry that I cannot help you much.

**Comment by Kaijun101** [comment]
Hi, @engcang thanks for your reply. I have actually email u some details about my project.
